name: Deploy on merge to main

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ secrets.REPO_NAME }}:latest
            ghcr.io/${{ secrets.REPO_NAME }}:${{ github.sha }}

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            set -e
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Stop and remove old container if exists
            docker stop bpi-to-rss || true
            docker rm bpi-to-rss || true

            # Pull latest image
            docker pull ghcr.io/la-forge/bpi-to-rss:${{ github.sha }}

            # Run the new container (adjust ports/volumes/env as needed)
            docker run -d --name bpi-to-rss -p 8000:8000 \
              ghcr.io/la-forge/bpi-to-rss:${{ github.sha }}