name: Run Unit Tests with Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"] # Specify the Python versions you want to test against

    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }} 

      - name: Install dependencies
        run: |
          uv sync
          uv add pytest==8.11
      - name: Run tests with pytest
        run: |
          pytest
