name: Run Unit Tests with Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: |
          uv sync
          uv add pytest==8.11
      - name: Run tests with pytest
        run: |
          pytest
